include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    cascade_invocations: false

analyzer:
  errors:
    missing_required_param: error

  exclude:
    - lib/src/country.dart